# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TracesWindow(object):
    def setupUi(self, TracesWindow):
        TracesWindow.setObjectName("TracesWindow")
        TracesWindow.resize(483, 483)
        self.centralwidget = QtWidgets.QWidget(TracesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view = TableView(self.centralwidget)
        self.view.setObjectName("view")
        self.verticalLayout.addWidget(self.view)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calculateKIDbutton = QtWidgets.QPushButton(self.frame)
        self.calculateKIDbutton.setObjectName("calculateKIDbutton")
        self.horizontalLayout.addWidget(self.calculateKIDbutton)
        spacerItem = QtWidgets.QSpacerItem(197, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.totalView = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalView.sizePolicy().hasHeightForWidth())
        self.totalView.setSizePolicy(sizePolicy)
        self.totalView.setReadOnly(True)
        self.totalView.setObjectName("totalView")
        self.horizontalLayout.addWidget(self.totalView)
        self.verticalLayout.addWidget(self.frame)
        TracesWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TracesWindow)
        self.statusbar.setObjectName("statusbar")
        TracesWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(TracesWindow)
        self.toolBar.setObjectName("toolBar")
        TracesWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.createChannelAction = QtWidgets.QAction(TracesWindow)
        self.createChannelAction.setObjectName("createChannelAction")
        self.deleteChannelAction = QtWidgets.QAction(TracesWindow)
        self.deleteChannelAction.setObjectName("deleteChannelAction")
        self.toolBar.addAction(self.createChannelAction)
        self.toolBar.addAction(self.deleteChannelAction)

        self.retranslateUi(TracesWindow)
        self.createChannelAction.triggered.connect(TracesWindow.createChannel)
        self.deleteChannelAction.triggered.connect(TracesWindow.destroyChannel)
        QtCore.QMetaObject.connectSlotsByName(TracesWindow)

    def retranslateUi(self, TracesWindow):
        _translate = QtCore.QCoreApplication.translate
        TracesWindow.setWindowTitle(_translate("TracesWindow", "Трассы"))
        self.calculateKIDbutton.setText(_translate("TracesWindow", "Рассчитать КИД"))
        self.label.setText(_translate("TracesWindow", "Итого:"))
        self.toolBar.setWindowTitle(_translate("TracesWindow", "toolBar"))
        self.createChannelAction.setText(_translate("TracesWindow", "Создать канал связи"))
        self.deleteChannelAction.setText(_translate("TracesWindow", "Удалить канал связи"))
from tableview import TableView
