# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TracesWindow(object):
    def setupUi(self, TracesWindow):
        TracesWindow.setObjectName("TracesWindow")
        TracesWindow.resize(483, 483)
        self.centralwidget = QtWidgets.QWidget(TracesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view = QtWidgets.QTableView(self.centralwidget)
        self.view.setObjectName("view")
        self.horizontalLayout.addWidget(self.view)
        TracesWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TracesWindow)
        self.statusbar.setObjectName("statusbar")
        TracesWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(TracesWindow)
        self.toolBar.setObjectName("toolBar")
        TracesWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.createChannelAction = QtWidgets.QAction(TracesWindow)
        self.createChannelAction.setObjectName("createChannelAction")
        self.deleteChannelAction = QtWidgets.QAction(TracesWindow)
        self.deleteChannelAction.setObjectName("deleteChannelAction")
        self.toolBar.addAction(self.createChannelAction)
        self.toolBar.addAction(self.deleteChannelAction)

        self.retranslateUi(TracesWindow)
        self.createChannelAction.triggered.connect(TracesWindow.createChannel)
        self.deleteChannelAction.triggered.connect(TracesWindow.destroyChannel)
        QtCore.QMetaObject.connectSlotsByName(TracesWindow)

    def retranslateUi(self, TracesWindow):
        _translate = QtCore.QCoreApplication.translate
        TracesWindow.setWindowTitle(_translate("TracesWindow", "Трассы"))
        self.toolBar.setWindowTitle(_translate("TracesWindow", "toolBar"))
        self.createChannelAction.setText(_translate("TracesWindow", "Создать канал связи"))
        self.deleteChannelAction.setText(_translate("TracesWindow", "Удалить канал связи"))
